/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author quemu
 */
public class FormManPay extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormManUser2
     */
    public FormManPay() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnlInternalbox = new javax.swing.JPanel();
        txtPaydate = new javax.swing.JFormattedTextField();
        lblPaydate = new javax.swing.JLabel();
        lblPayid = new javax.swing.JLabel();
        txtPayrid = new javax.swing.JTextField();
        txtClientname = new javax.swing.JTextField();
        lblClientname = new javax.swing.JLabel();
        txtPayfull = new javax.swing.JFormattedTextField();
        lblPayfull = new javax.swing.JLabel();
        txtPaydiscount = new javax.swing.JFormattedTextField();
        lblPaydiscount = new javax.swing.JLabel();
        cbxPaymode = new javax.swing.JComboBox<>();
        lblPaymode = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtPayrate = new javax.swing.JFormattedTextField();
        lblPayrate = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Gerenciar Pagamento");
        setMinimumSize(new java.awt.Dimension(300, 225));

        PnlInternalbox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtPaydate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("##/##/####"))));
        txtPaydate.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        lblPaydate.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblPaydate.setText("Data de vencimento");

        lblPayid.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblPayid.setText("Código");

        txtPayrid.setEditable(false);
        txtPayrid.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        txtClientname.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        lblClientname.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblClientname.setText("Nome do Cliente");

        txtPayfull.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("##/##/####"))));
        txtPayfull.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        lblPayfull.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblPayfull.setText("Total");

        txtPaydiscount.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("##/##/####"))));
        txtPaydiscount.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        lblPaydiscount.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblPaydiscount.setText("Desconto");

        cbxPaymode.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cbxPaymode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblPaymode.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblPaymode.setText("Forma de pagamento");

        txtPayrate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("##/##/####"))));
        txtPayrate.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        lblPayrate.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblPayrate.setText("Juros");

        javax.swing.GroupLayout PnlInternalboxLayout = new javax.swing.GroupLayout(PnlInternalbox);
        PnlInternalbox.setLayout(PnlInternalboxLayout);
        PnlInternalboxLayout.setHorizontalGroup(
            PnlInternalboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlInternalboxLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(PnlInternalboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator1)
                    .addComponent(lblPayid)
                    .addComponent(txtPayrid, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PnlInternalboxLayout.createSequentialGroup()
                        .addGroup(PnlInternalboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblClientname)
                            .addComponent(txtClientname, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPaymode)
                            .addComponent(cbxPaymode, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PnlInternalboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PnlInternalboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtPaydiscount, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                                .addComponent(lblPaydiscount))
                            .addGroup(PnlInternalboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtPaydate)
                                .addComponent(lblPaydate)
                                .addComponent(txtPayfull, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblPayfull))
                            .addGroup(PnlInternalboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtPayrate, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                                .addComponent(lblPayrate)))))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        PnlInternalboxLayout.setVerticalGroup(
            PnlInternalboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlInternalboxLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(lblPayid)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPayrid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PnlInternalboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PnlInternalboxLayout.createSequentialGroup()
                        .addComponent(lblPaydate)
                        .addGap(29, 29, 29))
                    .addComponent(txtPaydate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PnlInternalboxLayout.createSequentialGroup()
                        .addComponent(lblClientname)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtClientname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(PnlInternalboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlInternalboxLayout.createSequentialGroup()
                        .addComponent(lblPaymode)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxPaymode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PnlInternalboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(PnlInternalboxLayout.createSequentialGroup()
                            .addComponent(lblPaydiscount)
                            .addGap(29, 29, 29))
                        .addComponent(txtPaydiscount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(PnlInternalboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PnlInternalboxLayout.createSequentialGroup()
                        .addComponent(lblPayrate)
                        .addGap(29, 29, 29))
                    .addComponent(txtPayrate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnlInternalboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PnlInternalboxLayout.createSequentialGroup()
                        .addComponent(lblPayfull)
                        .addGap(29, 29, 29))
                    .addComponent(txtPayfull, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addComponent(PnlInternalbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(PnlInternalbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PnlInternalbox;
    private javax.swing.JComboBox<String> cbxPaymode;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblClientname;
    private javax.swing.JLabel lblPaydate;
    private javax.swing.JLabel lblPaydiscount;
    private javax.swing.JLabel lblPayfull;
    private javax.swing.JLabel lblPayid;
    private javax.swing.JLabel lblPaymode;
    private javax.swing.JLabel lblPayrate;
    private javax.swing.JTextField txtClientname;
    private javax.swing.JFormattedTextField txtPaydate;
    private javax.swing.JFormattedTextField txtPaydiscount;
    private javax.swing.JFormattedTextField txtPayfull;
    private javax.swing.JFormattedTextField txtPayrate;
    private javax.swing.JTextField txtPayrid;
    // End of variables declaration//GEN-END:variables
}
